const greetings =[
"Welcome to Recipe Realm! Ready to discover delicious recipes?",
"Hi there! Let's cook up something amazing together!",
"Hello! Excited to help you find the perfect recipe.",
"Welcome! How can I assist you with your cooking today?",
"Hey! Let's explore some mouthwatering recipes.",
"Greetings! Let's get cooking with Recipe Realm.",
"Hi! I'm here to help you find recipes that match your ingredients.",
"Hello there! Ready to dive into the world of culinary delights?",
"Welcome to Recipe Realm! Let's cook up a storm.",
"Hey there! Let's find some recipes you'll love.",
"Hello! Ready to explore tasty recipes with me?",
"Hi! I'm your cooking assistant. What's on the menu today?",
"Greetings! Let's whip up some delicious dishes together.",
"Welcome to Recipe Realm! What ingredients do you have?",
"Hi there! Let's find some recipes that suit your taste.",
"Hello! Excited to help you create culinary masterpieces.",
"Hey! Let's discover new flavors and recipes together.",
"Welcome! Let's find recipes that match your ingredients.",
"Hi! Ready to embark on a culinary adventure?",
"Hello! Let's cook something wonderful today.",
"Greetings! I'm here to help you with your cooking journey.",
"Hi there! Let's find the perfect recipe for you.",
"Welcome to Recipe Realm! What can I help you cook today?",
"Hey! Let's explore some amazing recipes together.",
"Hello! I'm excited to assist you with your culinary endeavors.",
"Hi! Let's discover some delicious recipes.",
"Greetings! Ready to discover new tastes and flavors?",
"Welcome! Let's cook up some magic in the kitchen.",
"Hi there! Let's make cooking easy and fun.",
"Hello! Let's find the perfect recipe for your ingredients.",
"Hey! Excited to help you find recipes you'll love.",
"Welcome to Recipe Realm! What dish are you craving today?",
"Hi! Let's create delicious memories with great recipes.",
"Hello! Ready to find recipes that match your style?",
"Greetings! Let's explore the world of culinary delights.",
"Hi there! Let's find recipes that inspire you.",
"Welcome! Let's cook something special together.",
"Hey! Let's make cooking simpler and more enjoyable.",
"Hello! Let's find the best recipes for your ingredients.",
"Hi! Ready to explore a world of tasty possibilities?",
"Greetings! Let's create something delicious today.",
"Welcome to Recipe Realm! Let's find recipes tailored for you.",
"Hi there! Let's uncover recipes that match your preferences.",
"Hello! Let's make cooking easier with great recipes.",
"Hey! Ready to discover new flavors and recipes?",
"Welcome! Let's find recipes that fit your taste.",
"Hi! Let's cook up something amazing together.",
"Hello! Excited to help you find the perfect recipe.",
"Greetings! I'm here to assist you with your cooking journey.",
"Hi there! Let's explore some delicious recipes.",
"Welcome to Recipe Realm! What can I help you cook today?",
"Hey! Let's find recipes that match your ingredients.",
"Hello! Let's cook something wonderful today.",
"Hi there! Let's make cooking easy and enjoyable.",
"Greetings! Let's explore the world of culinary delights.",
"Hello! I'm your cooking assistant. What's on the menu today?",
"Hey! Let's discover new flavors and recipes together.",
"Welcome! Let's find recipes that match your ingredients.",
"Hi there! Let's cook up a storm in the kitchen.",
"Hello! Ready to embark on a culinary adventure?",
"Greetings! Let's whip up some delicious dishes together.",
"Hi! I'm here to help you find recipes that suit your taste.",
"Hey! Let's explore some mouthwatering recipes.",
"Welcome to Recipe Realm! Let's cook something amazing.",
"Hello! Let's find the perfect recipe for your ingredients.",
"Hi! Ready to discover new tastes and flavors?",
"Greetings! Let's create something delicious today.",
"Hey there! Let's make cooking simpler and more fun.",
"Welcome! Let's cook up a feast together.",
"Hi! Let's find recipes that inspire your culinary creativity.",
"Hello! Excited to assist you with your cooking endeavors.",
"Hey! Let's uncover recipes you'll love cooking.",
"Welcome to Recipe Realm! Let's make cooking enjoyable.",
"Hi there! Let's explore the world of tasty recipes.",
"Hello! Ready to find recipes that match your style?",
"Greetings! Let's cook something special today.",
"Hi! Let's create delicious dishes with great recipes.",
"Hey! Let's find recipes that fit your culinary preferences.",
"Welcome! Let's make cooking easier and more fun.",
"Hello! Let's cook up some magic in the kitchen.",
"Hi there! Let's find recipes that suit your taste buds.",
"Greetings! I'm your cooking assistant. What's cooking?",
"Hey! Let's explore new flavors and cooking techniques.",
"Welcome to Recipe Realm! Let's discover tasty recipes.",
"Hi! Let's cook something delicious together.",
"Hello! Excited to help you with your cooking journey.",
"Hey there! Let's find the perfect recipe for you.",
"Greetings! Ready to create culinary masterpieces?",
"Hi! Let's make cooking fun and enjoyable.",
"Hello! Let's uncover recipes that match your preferences.",
"Hey! Let's find recipes that inspire your culinary creativity.",
"Welcome! Let's cook something amazing today.",
"Hi there! Let's explore delicious recipes together.",
"Hello! Ready to find recipes that suit your style?",
"Greetings! Let's cook up some tasty dishes.",
"Hi! Let's make cooking an adventure.",
"Hey! Let's discover new recipes you'll love.",
"Welcome! Let's find recipes that match your ingredients.",
"Hello! Excited to help you with your cooking journey.",
"Hi there! Let's cook up a storm in the kitchen."
];

export default greetings;
