const funFacts = [
    "Pineapples: the only fruit that wears a crown and dares you to touch its spiky throne!",
    "Carrots were originally purple until they got embarrassed and turned orange.",
    "Cake: The only reason to believe that cutting something can make you happier.",
    "Cheese is like a good friend - it's always there to melt your heart!",
    "The world's largest pizza was made in Rome in 2012, measuring 1261 square meters (13,570 square feet).",
    "Peanuts are not actually nuts; they are legumes related to beans and lentils.",
    "Bananas are berries, but strawberries are not.",
    "An average ear of corn has an even number of rows, usually 16.",
    "It is impossible to make a cup of tea from a coffee tree.",
    "Ketchup was sold in the 1830s as medicine.",
    "White chocolate isn't technically chocolate—it doesn't contain cocoa solids.",
    "Lettuce is a member of the sunflower family and is related to artichokes.",
    "Sweet potatoes are not actually potatoes; they belong to a different plant family.",
    "Vanilla comes from orchids and is the second most expensive spice after saffron.",
    "There are over 2,000 varieties of cheese worldwide, each with its own unique taste and texture.",
    "Garlic is known to ward off vampires, but it also has natural antibiotic properties.",
    "The most popular ice cream flavor is vanilla, followed closely by chocolate.",
    "There are over 600 different shapes of pasta produced worldwide.",
    "Saffron, derived from the crocus flower, is the most expensive spice in the world by weight.",
    "Broccoli is actually a flower that hasn't yet bloomed.",
    "Lemons contain more sugar than strawberries.",
    "Mushrooms are more closely related to humans than they are to plants.",
    "Pumpkins are a fruit, not a vegetable.",
    "Cinnamon comes from the bark of trees in the genus Cinnamomum.",
    "Coconut water can be used as a substitute for blood plasma.",
    "Tomatoes were once considered poisonous because they belong to the nightshade family.",
    "Carrots were originally purple, not orange.",
    "Broccoli contains more protein per calorie than steak.",
    "Garlic is known to have antibacterial and antiviral properties.",
    "Spinach is a great source of iron, but it's better absorbed when eaten with vitamin C-rich foods.",
    "Bell peppers come in various colors with different flavors: green, red, yellow, and orange.",
    "Onions contain a natural sugar called fructans, which can sometimes cause bloating.",
    "Cucumbers are 95% water, making them a great hydrating snack.",
    "Avocados are technically berries.",
    "Mushrooms are the only non-animal source of vitamin D.",
    "Sweet potatoes and yams are different vegetables, though they are often confused.",
    "Brussels sprouts contain more vitamin C than an orange.",
    "Kale has more calcium per calorie than milk.",
    "Asparagus can make your urine smell due to the sulfurous compound asparagusic acid.",
    "Eggplants are botanically classified as berries.",
    "Beets are rich in nitrates, which can help lower blood pressure.",
    "Celery is so low in calories that eating it can sometimes result in a negative calorie balance.",
    "Chili peppers contain capsaicin, which can boost metabolism.",
    "Lettuce was first cultivated by the ancient Egyptians.",
    "Radishes are related to wasabi, horseradish, and mustard.",
    "Cauliflower can come in white, green, purple, and orange varieties.",
    "Zucchini is technically a fruit, not a vegetable.",
    "Okra is known for its mucilaginous texture, which can thicken soups and stews.",
    "Pumpkins are a type of squash.",
    "Parsnips are related to carrots but have a sweeter, nuttier flavor.",
    "Bok choy is a type of Chinese cabbage.",
    "Peas are actually legumes, not vegetables.",
    "Turnips have been cultivated for over 4,000 years.",
    "Artichokes are actually flower buds.",
    "Cabbage leaves were used as a hangover cure in ancient Rome.",
    "Green beans are also known as string beans or snap beans.",
    "Rhubarb leaves are poisonous due to high levels of oxalic acid.",
    "Corn is one of the most widely grown crops in the world.",
    "Squash comes in both summer and winter varieties.",
    "Fennel has a licorice-like flavor and is related to carrots.",
    "Chayote is a type of squash that is often used in Mexican cuisine.",
    "Leeks are related to onions and garlic.",
    "Watercress is one of the oldest known leaf vegetables consumed by humans.",
    "Swiss chard is often used as a substitute for spinach in recipes.",
    "Endive is a type of chicory.",
    "Arugula is also known as rocket.",
    "Collard greens are a staple in Southern U.S. cuisine.",
    "Dandelion greens are edible and can be used in salads.",
    "Mustard greens have a peppery flavor and are rich in vitamins A, C, and K.",
    "Jicama is a root vegetable with a sweet, nutty flavor.",
    "Jerusalem artichokes are also known as sunchokes.",
    "Radicchio is a type of chicory with a bitter taste.",
    "Kohlrabi is also known as a German turnip.",
    "Bitter melon is commonly used in Asian cuisine.",
    "Seaweed is a rich source of iodine, which is essential for thyroid health.",
    "Spirulina is a type of blue-green algae that is often used as a dietary supplement.",
    "Nori is a type of seaweed used in sushi.",
    "Chlorella is a type of green algae used as a supplement.",
    "Wakame is a type of seaweed often used in Japanese soups.",
    "Hijiki is a type of seaweed that is high in dietary fiber.",
    "Agar-agar is a vegetarian gelatin substitute made from seaweed.",
    "Irish moss is a type of red seaweed used as a thickening agent.",
    "Kelp is a large, brown seaweed that grows in underwater forests.",
    "Napa cabbage is a type of Chinese cabbage.",
    "Mizuna is a type of Japanese mustard green.",
    "Shiso is a type of Japanese herb related to mint.",
    "Daikon is a type of large, white radish used in Asian cuisine.",
    "Lotus root is a common ingredient in Asian dishes.",
    "Bamboo shoots are the edible shoots of the bamboo plant.",
    "Ginger has been used for its medicinal properties for thousands of years.",
    "Turmeric is a key ingredient in curry powder and has anti-inflammatory properties.",
    "Coriander seeds are the dried seeds of the cilantro plant.",
    "Fenugreek seeds are often used in Indian cuisine.",
    "Cumin is a key spice in many global cuisines.",
    "Caraway seeds are often used in bread and pastries.",
    "Cardamom is a spice commonly used in Indian and Middle Eastern cuisine.",
    "Cinnamon is made from the inner bark of trees from the Cinnamomum genus.",
    "Cloves are dried flower buds used as a spice.",
    "Nutmeg is made from the seed of the nutmeg tree.",
    "Mace is made from the outer covering of the nutmeg seed.",
    "Saffron is the most expensive spice in the world by weight.",
    "Vanilla is derived from orchids of the genus Vanilla.",
    "Peppercorns come in black, white, green, and pink varieties.",
    "Paprika is made from ground bell peppers or chili peppers.",
    "Mustard seeds are used to make mustard and are also a spice.",
    "Anise has a licorice-like flavor and is often used in baking.",
    "Star anise is used in Chinese five-spice powder.",
    "Allspice is made from the dried berries of the Pimenta dioica plant.",
    "Juniper berries are used to flavor gin.",
    "Sumac is a tangy spice used in Middle Eastern cuisine.",
    "Tamarind is used to add a sour flavor to dishes.",
    "Sesame seeds are often used in Asian cuisine and to make tahini.",
    "Flaxseeds are high in omega-3 fatty acids.",
    "Chia seeds are high in fiber and omega-3 fatty acids.",
    "Pumpkin seeds are a good source of protein and magnesium.",
    "Sunflower seeds are high in vitamin E.",
    "Hemp seeds are a complete source of protein.",
    "Quinoa is a complete protein and is technically a seed, not a grain.",
    "Amaranth is an ancient grain high in protein.",
    "Buckwheat is gluten-free and often used in pancakes and soba noodles.",
    "Millet is a gluten-free grain often used in birdseed but also eaten by humans.",
    "Teff is a tiny grain used to make Ethiopian injera bread.",
    "Sorghum is a gluten-free grain often used in cereals and as a sweetener.",
    "Barley is one of the oldest cultivated grains.",
    "Oats are a good source of soluble fiber, which can help lower cholesterol.",
    ];

const shuffleArray = (array) => {
  let shuffledArray = [...array];
  for (let i = shuffledArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
  }
  return shuffledArray;
};

const getDistinctFacts = (count) => {
  const shuffledFacts = shuffleArray(funFacts);
  return shuffledFacts.slice(0, count);
};

export const distinctFacts = getDistinctFacts(4); // Get 4 distinct facts
